[project]
name = "pc-ai-operator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "browser-use>=0.1.37",
    "pyperclip>=1.9.0",
    "ruff>=0.9.6",
]
